toroboarm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  # joint1_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: first_joint
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
  # joint2_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: second_joint
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
  # joint3_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: third_joint
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
  # joint4_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: fourth_joint
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
  # joint5_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: fifth_joint
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
  # joint6_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: sixth_joint
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
  # joint7_position_controller:
  #   type: position_controllers/JointPositionController
  #   joint: seventh_joint
  #   pid: {p: 100.0, i: 0.01, d: 10.0}

  whole_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - first_joint
      - second_joint
      - third_joint
      - fourth_joint
      - fifth_joint
      - sixth_joint
      - seventh_joint
