toroboarm_gripper:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  whole_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - first_joint
      - second_joint
      - third_joint
      - fourth_joint
      - fifth_joint
      - sixth_joint
      - seventh_joint

  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - right_finger_joint
      - left_finger_joint
